### ISSUE TITLE
Events double dispatching support

### ISSUE THREAD

**Issue by nameofuser1** [digint/tinyfsm#17]
What do you think about making Events to be double dispatch-able? For now it is necessary to explicitly specify event type when dispatching event, however since it is c++ library it can be useful to take advantage of polymorphic events.

**Comment by digint** [comment]
TinyFSM does not limit `Fsm::dispatch()` to any type, this simply calls `State::react()` of the current state with the given type (which does not necessarily needs to be derived from `tinyfsm::Event`).

I'm not sure what you mean by "double dispatchable", maybe you can elaborate this with a short example?

**Comment by digint** [comment]
answered, added "wontfix" label (as there is nothing to fix ;-)

**Comment by mo-krauti** [comment]
I think I did what you wanted in #46. But why should it not be applicable, have I misunderstood something?
