### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by JWaynee** [digint/tinyfsm#23]
Hello,

I have some troubles using the fsm. When I compile the elevator example in the console using make everything compiles fine. When I make a new project in Qt Creator I get a linker error undefined reference to tinyfsm::Fsm<Motor>::set_initial_state(). 
Can somebody tell what the reason is for this?

Thanks in advance
John

**Comment by JWaynee** [comment]
Okay figured it out. I need to include the motor.cpp and elevator.cpp files into main.
Is there a reason why they are not declared in the corresponding .hpp files?

**Comment by digint** [comment]
>  Is there a reason why the state classes are not declared in the corresponding .hpp files?

I would say the main reason is because there is no much benefit in doing so. Secondly, they are not meant to be exported: optimized within the templates in `tinyfsm.hpp` at compile time.

**Comment by digint** [comment]
answered, closing ticket
